<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
		<RestoreAdditionalProjectSources>
			https://api.nuget.org/v3/index.json;
			https://nuget.bepinex.dev/v3/index.json;
			https://nuget.samboy.dev/v3/index.json
		</RestoreAdditionalProjectSources>
    </PropertyGroup>

    <ItemGroup>
      <Compile Remove="libs\**" />
      <EmbeddedResource Remove="libs\**" />
      <None Remove="libs\**" />
    </ItemGroup>

	<ItemGroup>
		<PackageReference Include="BepInEx.Unity.IL2CPP" Version="6.0.0-be.*" IncludeAssets="compile" />
		<PackageReference Include="SOD.Common" Version="2.1.0" />
	</ItemGroup>

	<ItemGroup>
	  <Reference Include="Assembly-CSharp">
	    <HintPath>D:\Program Files (x86)\Steam\steamapps\common\Shadows of Doubt\BepInEx\interop\Assembly-CSharp.dll</HintPath>
	  </Reference>
	  <Reference Include="Il2Cppmscorlib">
	    <HintPath>D:\Program Files (x86)\Steam\steamapps\common\Shadows of Doubt\BepInEx\interop\Il2Cppmscorlib.dll</HintPath>
	  </Reference>
	  <Reference Include="Il2CppSystem">
	    <HintPath>D:\Program Files (x86)\Steam\steamapps\common\Shadows of Doubt\BepInEx\interop\Il2CppSystem.dll</HintPath>
	  </Reference>
	  <Reference Include="Il2CppSystem.Core">
	    <HintPath>D:\Program Files (x86)\Steam\steamapps\common\Shadows of Doubt\BepInEx\interop\Il2CppSystem.Core.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine">
	    <HintPath>D:\Program Files (x86)\Steam\steamapps\common\Shadows of Doubt\BepInEx\interop\UnityEngine.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.CoreModule">
	    <HintPath>D:\Program Files (x86)\Steam\steamapps\common\Shadows of Doubt\BepInEx\interop\UnityEngine.CoreModule.dll</HintPath>
	  </Reference>
	</ItemGroup>

</Project>
